name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fix permissions
        run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE && sudo chmod -R 755 $GITHUB_WORKSPACE

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libffi-dev libssl-dev

      - name: Build APK
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install buildozer
          buildozer android debug
     
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: MyApp
          path: bin/*.apk
